<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INHYNRBORA1" name="Test2" tests="4" failures="4" timestamp="13 Jun 2019 09:59:10 GMT" time="0.035" errors="0">
  <testcase name="test2" time="0.006" classname="reRunFailedTestCase.Test2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at reRunFailedTestCase.Test2.test2(Test2.java:10)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="reRunFailedTestCase.Test2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at reRunFailedTestCase.Test2.test2(Test2.java:10)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="reRunFailedTestCase.Test2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at reRunFailedTestCase.Test2.test2(Test2.java:10)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="reRunFailedTestCase.Test2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at reRunFailedTestCase.Test2.test2(Test2.java:10)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test2 -->
